---
- name: Install libselinux-python
  yum:
    name: libselinux-python
    state: present
    when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7"
 
- name: Install libselinux-python
  yum:
    name: python3-libselinux
    state: present
    when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "8"

- name: Disable SELinux
  selinux:
    state: disabled
